server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ymgczh/microservicecloud-config.git
          username: 1026467712@qq.com
          password: ZHANGSHImushi199