server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: getway-9527.com    #自定义服务名称 #显示访问IP
    prefer-ip-address: true


info:
  app.name: zhymgc-cloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: microservicecloud-zuul-gateway
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept
